services:
  wireguard:
    image: linuxserver/wireguard:version-v1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - "9091:9091/tcp"
    volumes:
      - /data/wireguard/wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: always
  transmission:
    image: linuxserver/transmission:version-3.00-r5
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    env_file:
      - ./stack.env
    volumes:
      - /data/transmission/config:/config
      - /data/transmission:/downloads
      - /data/transmission/watch:/watch
    restart: always
