services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=cLHz+iLM3YW+PRgZcNnEIfiZV5kBUlgADpXu/ErKq0Y=
      - WIREGUARD_ADDRESSES=10.65.171.200/32
  curl:
    image: curlimages/curl
    network_mode: "service:gluetun"
